version: "3.9"

services:
    mostry:
        container_name: mostry
        build:
            context: ./docker_mostry
        volumes:
            - ./xroad_entur_custom:/usr/src/app/xroad_entur_custom:rw

        command: >
            sh -c " 
            pip list -v &&
            cd ./xroad_entur_custom &&
            python script_app.py
            "

volumes:
    xroad_entur_custom:
