version: "3.9"

services:
    mostry:
        container_name: mostry
        build:
            context: ./docker_file
        volumes:
            - ./xroad_entur_default:/usr/src/app/xroad_entur_default:rw

        command: >
            sh -c " 
            pip list -v &&
            cd ./xroad_entur_default &&
            python script_app.py "

volumes:
    xroad_entur_default:
